apiVersion: v1
kind: Pod
metadata:
  name: tweetreceiver-ms
  labels:
    app: tweetreceiver-ms
spec:
  nodeName: minikube
  containers:
  - name: tweetreceiver
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/workshop-event-bus-microservice-choreography-may-2018"
    - name: APP_PORT
      value: "8101"
    - name: APP_HOME
      value: "part4/TweetReceiver"
    - name: APP_STARTUP
      value: "TweetReceiver.js"
    - name: KAFKA_HOST
      value: "zookeeper.kafka"
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: KAFKA_TOPIC
      value: "workflowEvents"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8101
