apiVersion: v1
kind: Pod
metadata:
  name: tweet-translator-ms
  labels:
    app: tweet-translator-ms
spec:
  nodeName: minikube
  containers:
  - name: tweet-translator
    # get latest version of image
    image: lucasjellema/node-app-runner
    imagePullPolicy: IfNotPresent
    env:
    - name: GIT_URL
      value: "https://github.com/lucasjellema/workshop-event-bus-microservice-choreography-may-2018"
    - name: APP_PORT
      value: "8118"
    - name: APP_HOME
      value: "TweetTranslator"
    - name: APP_STARTUP
      value: "TweetTranslator.js"
    - name: KAFKA_HOST
      value: "zookeeper.kafka"
    - name: ZOOKEEPER_PORT
      value: "2181"
    - name: KAFKA_TOPIC
      value: "workflowEvents"
    - name: REDIS_HOST
      value: "redis-cache"
    - name: REDIS_PORT
      value: "6379"
    ports:
    # containerPort is the port exposed by the container (where nodejs express api is listening)
    - containerPort: 8118
    